# .github/workflows/build-with-bazel.yaml
name: Build with Bazel

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
            # Avoid downloading Bazel every time.
            bazelisk-cache: true
            # Store build cache per workflow.
            disk-cache: ${{ github.workflow }}-${{ matrix.os }}
            # Share repository cache between workflows.
            repository-cache: true

      - name: Build core
        run: bazel build @arrow//:arrow

      - name: Build parquet
        run: bazel build @arrow//:parquet

      - name: Build acero
        run: bazel build @arrow//:acero

      - name: Build csv
        run: bazel build @arrow//:csv

      - name: Build dataset
        run: bazel build @arrow//:dataset

      - name: Build filesystem
        run: bazel build @arrow//:filesystem

      - name: Build flight
        run: bazel build @arrow//:flight

      - name: Build flight_sql
        run: bazel build @arrow//:flight_sql

      - name: Build ipc
        run: bazel build @arrow//:ipc

      - name: Build engine
        run: bazel build @arrow//:engine
